#!/bin/bash

export ECI4FOAM_DIR=$(pwd)/ECI4FOAM
echo "ECI4FOAM_DIR:= $ECI4FOAM_DIR" 

./src/OF_FMU/pyFMUSim/Allwmake
wmake src/OF_FMU/FMU/


wmake application/solver/solidFoamAdjustTime/
wmake application/tools/dictModifier/

