#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

cp system/externalCouplingDict.bkp system/externalCouplingDict
cp system/decomposeParDict.bkp system/decomposeParDict
cp system/controlDict.bkp system/controlDict

runApplication $(getApplication) dictMod.json



#------------------------------------------------------------------------------
