destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/doc-pdf"
port: 4010
output: pdf
product: doc
print_title: Jekyll theme for documentation — doc product
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: doc_sidebar
