#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

function runCase () {
    restore0Dir

    touch fuelTruck.foam

    # m4 system/blockMeshDict.m4 > system/blockMeshDict
    runApplication blockMesh
    runApplication -s 1 transformPoints -scale 10
    runApplication -s 2 transformPoints -rollPitchYaw '(0 90 0)'

    runApplication setFields

    runApplication $(getApplication)
}

python FuelTruck_uncoupled.py
foamDictionary system/simulationParameters -entry pyFileName -set FuelTruck_coupled
runCase
# cleanCase0
# foamDictionary system/simulationParameters -entry pyFileName -set FuelTruck_uncoupled
# runCase
#------------------------------------------------------------------------------
