#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/CleanFunctions      # Tutorial clean functions
#------------------------------------------------------------------------------

cleanCase
rm controlledTemperature.csv ControlledTemperatureCoupled_FMU.* ControlledTemperatureCoupled.log
rm -r temp

#------------------------------------------------------------------------------
