#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

touch flange.foam

runApplication ansysToFoam \
    ${FOAM_TUTORIALS:?}/resources/geometry/flange.ans -scale 0.001

runApplication decomposePar

runParallel $(getApplication)


if false
then
    runParallel foamToEnsight -noZero
    runParallel foamToVTK
fi

#------------------------------------------------------------------------------
