name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  build-wrapper:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04] #, windows-latest]
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Compile wrapper on Windows
        if: startsWith(runner.os, 'Windows')
        run: |
          pip install conan
          cd $Env:github_workspace/FMU4FOAM/FMU4FOAM-export
          mkdir tmp-build
          conan install . -s build_type=Release --install-folder=tmp-build
          cd tmp-build
          cmake .. -DCMAKE_BUILD_TYPE=Release -A x64
          cmake --build . --config Release
          cd ..

      - name: Compile wrapper on Linux / macOS
        if: startsWith(runner.os, 'Linux') || startsWith(runner.os, 'macOS')
        run: |
          pip install conan
          cd $GITHUB_WORKSPACE/FMU4FOAM/FMU4FOAM-export
          mkdir tmp-build
          conan install . -s build_type=Release -s compiler.libcxx=libstdc++ --install-folder=tmp-build
          cd tmp-build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
          cd ..

      - name: Archive wrapper library
        uses: actions/upload-artifact@v2
        with:
          name: lib-wrapper
          path: FMU4FOAM/resources

  build-python:
    needs: build-wrapper
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Download wrappers
        uses: actions/download-artifact@v1
        with:
          name: lib-wrapper
          path: FMU4FOAM/resources
    
      - name: Build distribution artifacts
        run: |
          python -m pip install setuptools wheel
          python setup.py sdist bdist_wheel

      - name: Archive production artifacts
        uses: actions/upload-artifact@v1
        with:
          name: python-wheel
          path: dist

  test:
    needs: build-test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]#, windows-latest]
        python-version: [3.9] #[3.7, 3.8, 3.9]
        # exclude:
        #   - os: ubuntu-20.04
        #     python-version: 3.7
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v2

      - name: Download python package
        uses: actions/download-artifact@v1
        with:
          name: python-wheel

      - name: Setup Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
        
      - name: Run the Tests
        run: |
          conda activate test
          # Install test dependencies - update environment.yml if they changed
          conda env update --name=test --file=environment.yml
          cd python-wheel
          python -m pip install FMU4FOAM*.whl
          cd ..
          cd test
          fmu4foam build -f test-example.py -of damBreak/ --no-external-tool
          python test-omsim.py &
          python test-zmqclient.py

        shell: bash -l {0}

